### ISSUE TITLE
Nothing works after update! 

### ISSUE THREAD

**Issue by twisted-torque** [echocoderxbmc/plugin.video.xxx-o-dus#20]
Any menu I click movie, tubes, scenes I get error "scraping error, info added to the log file" and sometime "no content found" 

Link to log 
 https://paste.ubuntu.com/25296195/

**Comment by echocoderxbmc** [comment]
So if you open xxxodus and click Tubes it errors without showing any of the sites?

On the main menu at the bottom is an option for version debugging. Please click it and let me know the versions of the installed addons. Thanks

**Comment by twisted-torque** [comment]
No,  it goes to the tubes, scenes just fine, but it gives the errors once you go to the tube site, 

I will try to do the version debugging and report back

**Comment by echocoderxbmc** [comment]
Thank you it all sounds a bit odd to me because ive not seen this issue anywhere else so its a bit of a mind baffle.

Could you please try to uninstall xxxodus and then make sure to install it from the colossus repo please.

**Comment by twisted-torque** [comment]
Debug versions 
XXX-O-DUS 3.00.026
Scrapers 1.00.020
Artwork 1.00.017
Libraries: 1.00.003
UrlResolver 4.0.01
Adult Resolver : 1.0.07

**Comment by echocoderxbmc** [comment]
Hello, I have had a really good look through the log and every site you try to access gives back an SSL error issues like this:

13:03:48.220 T:139986998998784   DEBUG: XXX-O-DUS: Request-Error: (<urlopen error [Errno 1] _ssl.c:510: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number>) => https://www.4tube.com/tags

Due to the fact your on Linux I would come to the assumption that there is an issue in your python/ssl setup. Below is a link to reference some others with the same type of error you have.

https://stackoverflow.com/questions/29627991/1408f10bssl-routinesssl3-get-recordwrong-version-number-call-on-indy

Due to this being an issue with your setup and not the addon itself there is no other help I can offer but to advise you to research into the error above and try to fix it you end.
