### ISSUE TITLE
javtasty and bug report

### ISSUE THREAD

**Issue by babingez** [echocoderxbmc/plugin.video.xxx-o-dus#27]
Hi I cant see Javtasty any more in TUBES is it down or somewhere else, and I was able to view the open issues in the plugin screen but the resolved ones wouldn't open. 
Brilliant work - thank you

**Comment by echocoderxbmc** [comment]
Hi, 

JavTasty was removed due to a layout change and next pages now coming in POST, along with the resolver changing too. I will get around to adding it back in when I have some time.

I have fixed the issue with closed issues, it will be fixed in the next update. 

Thanks for letting me know.

Issue Closed.

**Comment by babingez** [comment]
Thank you very much for your swift answer and for the brilliant work. Take care :-)
